# Generated by Django 4.2.5 on 2023-09-30 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_back_hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('converted_text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Patient',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.AddField(
            model_name='consult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app_back_hospital.patient'),
        ),
    ]
