# Generated by Django 4.2.5 on 2023-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back_hospital', '0002_consult_rename_paciente_patient_delete_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='audio_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
